### ISSUE TITLE
Could you update with source code please.

### ISSUE THREAD

**Issue by mfallu** [kakauandme/anomalyfinder#1]
Hi - It would be great if you could upload the source code for your competition entry please.
Thanks,

Mark

**Comment by kakauandme** [comment]
Hi Mark,
I've just pushed our code. I'll try to clean it up tomorrow and add some comments.

Cheers,
Kirill

**Comment by kakauandme** [comment]
Hey Mark,

I've cleaned up the repository.

Now it contains all the necessary scripts and datasets.

Cheers,
Kirill
